name: safego
description: "A new Flutter project."

# publish_to: "none"

# version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  supabase: ^1.11.7
  http: ^1.3.0
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  url_launcher: ^6.2.5
  image_picker: ^1.0.0
  path: ^1.8.3
  path_provider: any
  mime: ^1.0.4
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0
  geocoding: ^2.1.0
  permission_handler: ^11.0.0
  telephony: ^0.2.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  # flutter_local_notifications: ^16.1.0
  # workmanager: any

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/MapAddress.jpg
